config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/users', to: 'users#index', as: 'users'
  get '/users/new', to: 'users#new'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'


  ########### Pictures ###########
  get '/pictures/new', to: 'pictures#new', as: 'new_picture'
  post '/pictures', to: 'pictures#create'
  get '/pictures', to: 'pictures#index'
  get '/pictures/:id', to: 'pictures#show', as: 'picture'

  ########### Pictures Tag ###########
  get '/picture_tags/new', to: 'picture_tags#new'
  post '/picture_tags', to: 'picture_tags#create'
  

########### Tags ###########

get '/tags', to: 'tags#index'
get '/tags/:id', to: 'tags#show', as: 'tag'

########### Comments ###########
get '/comments/new', to: 'comments#new', as: 'new_comment'
post '/comments', to: 'comments#create'
get '/comments/:id', to: 'comments#show', as: 'comment'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :picture_tags
    has_many :tags, through: :picture_tags
end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :picture_tags
    has_many :pictures, through: :picture_tags


    def self.most_popular
        self.all.map do |tag|
            tag.pictures.length
        end
    end




end

app/models/user.rb
class User < ApplicationRecord
    has_many :pictures
    has_many :comments, through: :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @comments = Comment.all
    @users = User.all
    @pictures = Picture.all
  end

  def create
    # create_comment = Comment.create(content: params[:content], user_id: params[:user_id], picture_id: params[:picture_id])
     create_comment = params.require(:comment).permit(:content, :picture_id, :user_id)
     @comment = Comment.create(create_comment)
    redirect_to comment_path(@comment.id)
  end

  def show
    @comment = Comment.find(params[:id])
    @user = User.find(params[:id])
  end
end

app/controllers/picture_tags_controller.rb
class PictureTagsController < ApplicationController
  def new
    @picture_tag = PictureTag.new
    @pictures = Picture.all
    @tags = Tag.all
  end

  def create
    new_picture = params(:picture_tag).permit(:picture_id, :tag_id)
    @picture_tag = PictureTag.create(new_picture)
    redirect_to picture_path(@picture_tag)

  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
    @tags = Tag.all
  end

  def show
    #  @picture_tag = PictureTag.find(params[:id])
     @picture = Picture.find(params[:id])
    # @comment = Comment.find(params[:id])
  end

  def new
    # byebug
    @tags = Tag.all
    @users = User.all
    @picture = Picture.new
    @tag = Tag.new
  end

  def create
        # byebug
       @picture = Picture.create(picture_params(:image_url, :title, :user_id))
      # redirect_to '/pictures/#{new_image.id}'
      redirect_to picture_path(@picture.id)
      
      
  end

  private

  def picture_params(*args)
    params.require(:picture).permit(:image_url, :title, :user_id)
  end




end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
    # redirect_to tag_path
  end

  def show
    @picture = Picture.find(params[:id])
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @pictures = Picture.all
  end
  
  
  def new
    @user = User.new
    @picture = Picture.new
  end

  def create
    # new_user = User.create(username: params[:username], email: params[:email], password: params[:password])
    # redirect_to "/users/#{new_user.id}"

    @user = User.create(user_params(:username, :email, :password))
    redirect_to user_path(@user.id)
  end

  def show
    # byebug
    @user = User.find(params[:id])
    @picture = User.find(params[:id])
  end

  private

  def user_params(*args)
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/picture_tags_helper.rb
module PictureTagsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>


<%= form_for @comment do |f| %>
    <%= f.collection_select :user_id, @users, :id, :username %>
    <%= f.label :picture, 'picture' %>
    <%= f.collection_select :picture_id, @pictures, :id, :title %>

    <%= f.label :content, 'content' %>
    <%= f.text_field :content %>
    
    <%= f.submit "Add Comment" %>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

<%= @user.username%>

<%= @comment.content %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnrollmentPorject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/picture_tags/create.html.erb
<h1>PictureTags#create</h1>
<p>Find me in app/views/picture_tags/create.html.erb</p>

app/views/picture_tags/new.html.erb
<h1>PictureTags#new</h1>
<p>Find me in app/views/picture_tags/new.html.erb</p>


<%= form_for @picture_tag do |f| %>
    <%= f.collection_select :picture_id, @pictures, :id, :image_url %>
    <%= f.collection_select :tag_id, @tags, :id, :name %>
    <%= f.submit "Add To Pictures"%>
  <% end %>

app/views/pictures/index.html.erb
<h1>Pictures#index</h1>
<p>Find me in app/views/pictures/index.html.erb</p>

<ul>
    <% @pictures.each do |picture_inst|%>
        <div><img src=<%=picture_inst.image_url%>  width="500" height="600"/></div>
        <div><%= link_to picture_inst.title, picture_path(picture_inst) %></div>
        <%end%>
        
</ul>

app/views/pictures/new.html.erb
<h1> this is the new page  </h1>



<%= form_for @picture do |f| %>
    <%= f.label :image, 'Your Image' %>
    <%= f.collection_select :tags, @tags, :id, :name %>
    <br/>
    <%= f.collection_select :user_id, @users, :id, :username %>
    <%= f.label :title, 'title' %>
    <%= f.text_field :title %>
    <%= f.text_field :image_url %>
    <%= f.submit "Create image" %>
<% end %>

app/views/pictures/show.html.erb
<h1>Picturesshow</h1>
<p>Find me in app/views/pictures/show.html.erb</p>



    <img alt= <%= @picture.title%> src=<%= @picture.image_url %>/>


    # add comment

   
<%= button_to "Create Comment", new_comment_path, :method => "get" %>






# image tag for the images
# show the tags for the image as a list

# add comment

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>


<ul>
<% @tags.map do |tag_ins| %>
    <li>
    <%= link_to tag_ins.name, tag_path(tag_ins)%>
    </li>
<%end%>
</ul>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

<h1>Tag Name: <%= @tag.name%></h1>


<%= image_tag (@picture.image_url), style:"height: 40%; width: 40%;"%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Im the index page</h1>

<ul>
  <% @users.each do |user_inst| %>
    <li>
      <%= link_to user_inst.username, user_path(user_inst) %>
    </li>
    <br>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Users</h1>
<p>Find me in app/views/users/new.html.erb</p>


<%= form_for @user do |f| %>
    username:
    <%= f.text_field :username%>
    email:
    <%= f.text_field :email%>
    password:
    <%= f.text_field :password%>
    <%= f.submit "login"%>
<%end%>

app/views/users/show.html.erb
<h1>All Pictures </h1>

<h1> Welcome User: <%=@user.username%></h1>



<h1>Create a new Picture</h1>



<% @user.pictures.each do |picture_inst|%>
    <li><img alt= <%= picture_inst.title %> src=<%= picture_inst.image_url %>/></li>
    <%= picture_inst.picture.title %>
    <br>
    
<%end%>

<%= button_to "Create Picture", new_picture_path, :method => "get" %>
 